Merge dev to main
rgolovachev/DSViz pull request #1
Opened 2023-03-16 09:35 UTC by rgolovachev

2023-03-16 13:27 UTC, DimaTrushin requested changes
В целом очень неплохо.
- Я думаю, что основная проблема в том, что ты сделал app, model, view, controller шаблонными. Это плохо бьется с Qt парадигмой, плюс ты все таки не можешь через интерфейс ввести произвольные данные типа T, под каждый тип данных у тебя свой интерфейс. Потому тут у тебя используются вещи конвертируемые в T из строки ввода. Так что можно избавиться от этой шаблонности и это все упростит.
- Еще по поводу обзервера, обрати внимание, что при подключении view должна оповещаться, а controller нет. Ну и интерфейсы ты там можешь убрать. Они по сути не нужны. std::function все и так делает. Тогда будет проще пользоваться портами.
- Еще посмотри про проброску функций в портах, чтобы не пересоздавать их в конструкторах дважды.
- Есть еще какие-то мелочи связанные с неконсистентностью оформления кода и другими вещами. Подключи clang-format. В идеале еще clang-tidy.

2023-03-16 13:27 UTC, DimaTrushin commented on DSViz.pro
> +QMAKE_CXXFLAGS += -O3
Вот это компиляторо зависимый флаг. Это либо gcc либо clang как я понимаю. Под msvc уровня 3 просто нет, а флаги оптимизации надо писать через /, то есть /O2 -- максимальный уровень. Так что тут стоит поставить проверку на компилятор.

2023-03-16 13:27 UTC, DimaTrushin commented on main.cpp
> +  DSViz::MainWindow win;
- В начале замечание. Идейно, про Qt экосистему надо думать так. QApplication это НЕ твое приложение, это объект, который инициализирует саму экосистему, создает фасад для взаимодействия с операционкой и всякие нужные тебе глобальные объекты. Он же отвечает за event loop (ты его собственно и запускаешь). Потому все остальные объекты, которые ты создаешь, ты создаешь до запуска event loop и "встраиваешь их" в экосистему Qt. И они уже взаимодействуют внутри event loop-а через сообщения.
- К чему я это все.
У тебя тут создается два объекта win и app, как два разных участника Qt экосистемы. Но на сколько я понимаю, app -- это твое приложение, а win -- это компонента Qt для отображения всего, что есть в ядре app. Потому для меня это выглядит ошибкой дизайна. А именно, win (MainWindow) это все таки детали имплементации View компоненты, которая должна лежать внутри твоего App, а не создаваться отдельно. Я воспринимаю app как контекст для выполнения всего в твоем приложении. Потому снаружи должны жить какие-то супер глобальные объекты, без которых твой app может функционировать, но без которых он не может правильно взаимодействовать с OS. Например обработчкики исключений. Но никак не графические компоненты.

2023-03-16 13:27 UTC, DimaTrushin commented on main.cpp
> +  DSViz::App<int> app{&win};
- Во-первых, странно выглядит, что у тебя App требует шаблонный параметр и этот параметр именно int. За что он тут отвечает совершенно не понятно. Если это параметр хранимых данных в дереве, то это не то место, где это данное должно настраиваться, просто app должен хранить в себе структуры нужного типа.
- Во-вторых, у тебя в pro файле не отключены исключения. Ты вообще говоря позволяешь их бросать? Если да, то тут нехватает обработки исключений в конструкторе app. Если нет, то надо отключить exception в pro файле.
- В-третьих, я посмотрел имплементацию app. Он хранит все свои данные на стеке. Если эти компоненты тяжелые, то ты можешь занять много места на стеке. Чтобы избежать заполонения стека, можно сделать pimpl. То есть ты внутри app хранишь unique_ptr на app_impl и переносишь в app_impl всю имплементацию. В данном случае это не имеет большого значения, но это общее соображение.

2023-03-16 13:27 UTC, DimaTrushin commented on main.cpp
> +  win.show();
Тут будет стороннее замечание. По поводу функции show надо понимать некоторые тонкости. Она по разному работает в разных операционных системах, но под Windows я вот какую вещь наблюдал. В Windows своя message driven экосистема и для взаимодействия с операционкой тебе надо создать на main thread-е некоторые компоненты для коммуникации и зарегистрировать их в OS. Так вот по моему опыту этой регистрацией занимается функция show. На что это может повлиять. Если ты хочешь в app делать какие-то системные hook-и в операционку, то ты их не можешь сделать до регистрации упомянутых выше компонент. И это совершенно не очевидно. Если возникакют какие-то проблемы с системными вызовами, то стоит функцию show вызывать как можно раньше (в конструкторе app например).

2023-03-16 13:27 UTC, DimaTrushin commented on App/mainwindow.h
> +#include <memory>
Не понятно, зачем тут этот include.
Если уж ты его делаешь, то оберни ui в std::unique_ptr. Я знаю, что Qt по умолчанию делает там сырой указатель. Но new и delete мне просто режут по сердцу, плюс не придется писать деструктор.

2023-03-16 13:27 UTC, DimaTrushin commented on App/mainwindow.cpp
По поводу Include
Я бы сгруппировал их следующим образом:
1) твои инклуды
2) инклуды 3d party библиотек
3) инклуды stl
И еще можно clang-format заставить их отсортировать.

2023-03-16 13:27 UTC, DimaTrushin commented on App/app.h
> +      : model_{}, view_{model_.GetPort(), MW}, controller_{view_.GetPort(),
Как я и догадывался, MainWindow у тебя является частью view, так что его можно создать просто внутри него. И внутри его конструктора вызывать show.

2023-03-16 13:27 UTC, DimaTrushin commented on Observer/observer.h
Общие замечания по дизайну.
1) С твоей архитектурой тебе по сути не нужны интерфейсы и лишние виртуальные вызовы. У тебя поведение observer настраивается через std::function, которая и так содержит виртуальный вызов. Поэтому можешь просто убрать интерфейсы.
2) Проблема хранения данных observable в std::any заключается в том, что у тебя нет контракта на тип данных в соединении. Тебе компилятор не ругнется, если ты случайно соединяешь не те порты. Собственно система типов позволяет этой проблемы избежать. Что можно сделать -- вместо std::any сделать шаблонный параметр -- тип передаваемых данных. И сделать эти классы шаблонными.
Другая неприятность std::any -- пользователю observer-а надо будет все время в лямбде самому распаковывать данные.
3) Я тут что-то прокомментировал по коду observer-а. Но в целом для твоих нужд этой имплементации хватает. И потому из содержательных изменений только (1) и (2) выше.

2023-03-16 13:27 UTC, DimaTrushin commented on Observer/observer.h
> +  std::any msg_;
А зачем ты хранишь данные в observer-е? Ты хоть где-то это используешь? Просто у тебя нет даже метода observer-а, который позволяет к ним достучаться. А методы observer-а никак не используют это данное, кроме как передают в std::function еще и по константной ссылке.

2023-03-16 13:27 UTC, DimaTrushin commented on Observer/observer.cpp
> +  list_observer_.push_back(observer);
При добавлении нового observer-а его бывает надо оповещать. Дело в том, что когда ты подсоединяешь view к model, ты хочешь, чтобы view синхронизировалась тут же с model в момент подключения. А вот когда ты подсоединяешь controller к view, ты обычно не хочешь оповещаться. Я так понимаю, ты просто руками оповещаешь view при подключении?

2023-03-16 13:27 UTC, DimaTrushin commented on Observer/observer.h
> +  Observer(IObservable *observable, std::function<void(const std::any &)> lmbd);
Плохая идея передавать в observer указатель на observable. Ты вообще хочешь уметь работать с отключенным observer-ом. Дело в том, что суть observer-а еще в том, чтобы ты мог динамически переподсоединять их, например когда пользователь создает новые окна или закрывает старые. Но тогда надо во всех методах проверять подключен ли ты. В твоем случае во всем этом нет необходимости. Это просто общие замечания.

2023-03-16 13:27 UTC, DimaTrushin commented on App/app.h
> +template <typename T> class App {
Я думаю, что шаблонный параметр внутри App можно просто явно указать. Просто потому что это единственная точка настройки этого параметра.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +private:
Ты не консистентен в стиле оформления классов. У тебя в одних объявлениях сначала идут приватные данные, потом публичные. В други объявлениях наоборот. Выбери один стиль. Например сначала публичный интерфейс, потом приватная часть и данные в конце, тогда еще и данные класса будет удобнее искать.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  ~Trees() {
Конструкторы и деструкторы лучше объявлять раньше всех, потому что это выделенные методы отвечающие за value semantics в классе.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  std::unique_ptr<IObservable> port_out_;
Если вспомнить мое замечание про то, что тебе интерфейсы не нужны, тут можно просто написать
```cpp
Observable port_out_;
```
и тебе не нужен менеджмент памяти.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +Model<T>::Model() : data_{}, port_out_{new Observable()}, next_id_{} {
когда используешь unique_ptr не используй new, пиши std::make_unique<Observable>().

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +Model<T>::Model() : data_{}, port_out_{new Observable()}, next_id_{} {
Дефолтные значения можно указать в списке объявления переменных, например
```cpp
static constexpr int default_id_value_ = 0;

Trees data_ = {};
Observable port_out_ = {};
int next_id_ = default_id_value_;
```

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  void destroy(PNode<T> root) {
Для больших деревьев можно словить stackoverflow. Но думаю, можно про это не париться.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  port_out_->Set(std::make_pair(StrMsg[MsgCode::INS_DONE], data_.Get()));
Вот тут кажется небольшая ошибка формата сообщения. Смотри, ты заполняешь информацию данными и строкой сообщения. Но твое дерево не должно париться по поводу строки сообщения. Оно может сообщить статус типо MsgCode о том, что операция сделана (INS_DONE) или что-то в этом духе, но какое писать сообщение, не его забота. По сути нужные сообщения должна писать view, а чтобы понять, как их писать, у нее должна быть компонента locale, которая умеет транслировать статусы в сообщения. И тогда тебе не нужна глобальная структура StrMsg, она превращается в компоненту view. И более того, если ты потом хочешь поддерживать несколько языков, то ты можешь ее обновлять через соединение observer/observable.
В сухом остатке, я бы ожидал, что тут ты посылаешь пару (статус операции, данные), а НЕ (строка сообщения, данные).

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  data_[id] = insert(data_[id], key, &flag);
Такой вопрос. У тебя operator[] может вставить в data_ новую дефолтную вершину, если value с ключем id еще не было. У тебя это как-то обрабатывается?

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  PNode<T> &operator[](int key) { return trees_[key]; }
Тебе ОК, что эта штука может вставить вершину в trees_, если key не существовал?

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +    return;
Я не вникал в то, как именно тут все работает. Потому задаю тупые вопросы.
Возникновение ошибки тут, оставляет дерево в валидном формате и можно продолжать работу с ним?

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +    data_[id] = new Node<T>{.par = nullptr,
Я так понимаю, что такое можно спрятать в статический метод и использовать так
```cpp
static PNode<T> make_hidden_node(PNode<T> ltree, PNode<T> rtree) {
  return new Node<T>{.par = nullptr,
                            .left = ltree,
                            .right = rtree,
                            .value = ltree->max,
                            .min = 0,
                            .max = 0,
                            .state = State::HIDE_THIS};
}
data_[id] = make_hidden_node(ltree, rtree);
```

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +  std::string msg = "The left tree ID is " + std::to_string(id) +
Мне не нравится, что дерево занимается лишней работой и само составляет сообщения. По хорошему она должна отправлять структуру с необходимыми данными, а уже view по ним построит сообщение.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +    port_out_->Set(std::make_pair(StrMsg[MsgCode::FOUND], data_.Get()));
Я посмотрел, у тебя внутри find есть отправка сообщения с кодом FOUND, а тут еще раз такая отправка после вызова find. Это не будет задваиванием сообщения?

2023-03-16 13:27 UTC, DimaTrushin commented on Core/model.h
> +    set_color(v, v->par->par->left, v->left, v->right, v->par->right);
UPD:
Я посмотрел имплементацию set_color. Оказалось, что у тебя просто неправильное название. Но старое сообщение я тоже оставил. Название твоего метода обманывает. Ты не устанавливаешь никакой цвет. Ты устанавливаешь статус вершин. Потому лучше было бы назвать метод set_status. В целом это тоже некая проблема, что дерево должно заниматься изменением статуса связанного с отрисовкой. Ну пусть у нас будет дерево со статусами. Это упрощает в целом коммуникацию модели и вьюхи.
OLD:
Это еще один момент, который мне не нравится. У тебя модель решает о том, какой будет цвет. Но по хорошему, цвет должен определяться палитрой внутри view, а палитра подбирает цвет по статусу и информации, которая пришла от модели.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/vnode.h
> +constexpr const int kRadius = 6;
По идее, когда тебе нужны какие-то константы для общих алгоритмов, это означает, что эти алгоритмы не должны быть свободными функциями. Они должны быть методами класса. Например вместо
```cpp
constexpr const int kData = 0;
void method1(){
  int x = kData;
  ...
}
void method2() {
  int y = kData;
  ...
}
```
Ты делаешь
```cpp
class Alg {
  static constexpr const int kDefaultData_ = 0;
public:
void method1(){
  int x = Data;
  ...
}
void method2() {
  int y = Data;
  ...
} 
private:
  int Data_ = kDefaultData_;
};
```
Тогда все твои глобальные константы будут скрыты внутри класса, их можно будет настраивать (добавив соответствующие методы), можно будет использовать методы с разными настройками в разных местах программы. В целом это общий метод избавления от глобальных констант.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/controller.h
> +    port_in_.reset(new Observer{observable, lambda});
Ты по сути дважды переконструируешь порт. Вместо этого нужно сделать метод, который возвращяет нужную лямбду и в конструкторе вызвать его
```cpp
Controller(IObservable *observable, Model<T> *model) : model_ptr_{model}, port_in_(observable, get_action()) {
  }
auto get_action() {
  return [this](const std::any &msg_) {
      UserQuery<T> msg = std::any_cast<UserQuery<T>>(msg_);
      if (msg.type == QueryType::INSERT) {
        this->Insert(msg.args);
      } else if (msg.type == QueryType::REMOVE) {
        this->Remove(msg.args);
      } else if (msg.type == QueryType::FIND) {
        this->Find(msg.args);
      } else if (msg.type == QueryType::SPLIT) {
        this->Split(msg.args);
      } else if (msg.type == QueryType::MERGE) {
        this->Merge(msg.args);
      } else if (msg.type == QueryType::DELTREE) {
        this->DeleteTree(msg.args);
      }
    };
}
```

2023-03-16 13:27 UTC, DimaTrushin commented on Core/controller.h
> +      if (msg.type == QueryType::INSERT) {
Только один вопрос: почему не switch?

2023-03-16 13:27 UTC, DimaTrushin commented on Core/controller.h
> +    auto lambda = [this](const std::any &msg_) {
Еще можно сделать идейно по-другому. Можно пробросить вызов метода из this, а именно
```cpp
auto lambda = [this](const std::any &msg) {
  this->handle_msg(msg);
}
```
И уже внутри Controller имплементировать метод handle_msg. Кроме того, при перехватке this писать this-> не обязательно, можно просто написать handle_msg(msg); и все. Кроме того, такую короткую лямбду можно тут же объявить в конструкторе.
Еще можно тут же кастануть данные из std::any в те данные, что нам нужны и в handle_msg уже обрабатывать данные без необходимости кастовать.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/view.h
> +
Все вот такие настройки для рисования надо прятать в объект Palette (палитра)

2023-03-16 13:27 UTC, DimaTrushin commented on Core/view.h
> +// определить макрос Q_OBJECT
На самом деле я думаю, что делать view, model и controller шаблонными была НЕ правильная идея. Можно было внутри них сделать в начале using для типа данных и имплементировать под этот тип данных. Один черт у тебя ввод пользователя заточен под int. Просто если обобщать на произвольные данные пользователя, тебе ж все равно надо будет формочку для MainWindow править, чтобы пользователь реально мог ввести данное не типа int, а какого-то более сложного вида. Так что если уж у тебя view шаблонная, то и интерфейс пользователя должен быть шаблонным, чтобы пользователь мог вводить любые данные T через этот интерфейс. А это явно кусок сильно больше, чем мы можем себе позволить проглотить. И плюс не бьется с парадигмой Qt о нешаблонных классах.

2023-03-16 13:27 UTC, DimaTrushin commented on Core/view.h
> +  if (std::is_same_v<T, int>) {
Ну вот и пошли костыли из-за шаблонной View. Это кстати if constexpr

2023-03-29 09:26 UTC, rgolovachev commented
Если что, пока еще не все готово, обработал только часть комментариев

2023-03-30 10:34 UTC, rgolovachev commented on DSViz.pro
> +QMAKE_CXXFLAGS += -O3
Подправил, теперь вроде как qmake должен уметь детектить компилятор и в зависимости от него выставлять флаги.

2023-03-30 10:35 UTC, rgolovachev commented on main.cpp
> +  DSViz::MainWindow win;
Засунул создание MainWindow и win.show() внутрь конструктора View

2023-03-30 10:36 UTC, rgolovachev commented on main.cpp
> +  DSViz::App<int> app{&win};
- Теперь App нешаблонный
- Отключил exception в pro файле
- Я верю что оно влезет на стек)

2023-03-30 10:37 UTC, rgolovachev commented on main.cpp
> +  win.show();
win.show() теперь делаю в конструкторе View, надеюсь это норм

2023-03-30 10:38 UTC, rgolovachev commented on App/mainwindow.h
> +#include <memory>
Завернул ui в std::unique_ptr

2023-03-30 10:42 UTC, rgolovachev commented on App/mainwindow.cpp
У меня стоит в qt creator clang-format и в качестве "Predefined style" выбран LLVM и оно сортит инклюды (возможно не в том порядке, в котором ты предложил).

2023-03-30 10:43 UTC, rgolovachev commented on App/app.h
> +      : model_{}, view_{model_.GetPort(), MW}, controller_{view_.GetPort(),
Так и сделал

2023-03-30 10:44 UTC, rgolovachev commented on Observer/observer.h
1. Убрал
2. Избавился от std::any, теперь Observer/Observable это шаблонные классы

2023-03-30 10:44 UTC, rgolovachev commented on Observer/observer.h
> +  std::any msg_;
Убрал msg_

2023-03-30 10:47 UTC, rgolovachev commented on Observer/observer.cpp
> +  list_observer_.push_back(observer);
Теперь оповещаю в Subscribe. Когда подсоединяю controller к view, то порт controller'a оповещается, но контроллер ничего не делает (так как в поле msg_ лежит сообщение типа QueryType::DO_NOTHING, и это сообщение я отправляю в конструкторе view (костыль немного получился) ).

2023-03-30 10:48 UTC, rgolovachev commented on Observer/observer.h
> +  Observer(IObservable *observable, std::function<void(const std::any &)> lmbd);
Теперь не передаю этот указатель в конструкторе

2023-03-30 10:48 UTC, rgolovachev commented on App/app.h
> +template <typename T> class App {
Теперь App нешаблонный

2023-03-30 10:49 UTC, rgolovachev commented on Core/model.h
> +private:
Вообще у меня стиль, как у тебя написано в мануале, но где-то возможно я упустил и оформил класс не так как нужно. Надеюсь сейчас с этим все норм.

2023-03-30 10:50 UTC, rgolovachev commented on Core/model.h
> +  ~Trees() {
Исправил

2023-03-30 10:50 UTC, rgolovachev commented on Core/model.h
> +  std::unique_ptr<IObservable> port_out_;
Исправил

2023-03-30 10:51 UTC, rgolovachev commented on Core/model.h
> +Model<T>::Model() : data_{}, port_out_{new Observable()}, next_id_{} {
Вроде теперь везде make_unique юзаю если имею дело с unique_ptr

2023-03-30 10:52 UTC, rgolovachev commented on Core/model.h
> +Model<T>::Model() : data_{}, port_out_{new Observable()}, next_id_{} {
Ок исправил

2023-03-30 10:52 UTC, rgolovachev commented on Core/model.h
> +  void destroy(PNode<T> root) {
Думаю, что чтобы накликать столько вершин и словить stackoverflow, надо слишком сильно упороться

2023-03-30 10:53 UTC, rgolovachev commented on Core/model.h
> +  port_out_->Set(std::make_pair(StrMsg[MsgCode::INS_DONE], data_.Get()));
Исправил, теперь отправляю пару вида MsgCode и std::map (a.k.a BareTrees<int>)

2023-03-30 10:56 UTC, rgolovachev commented on Core/model.h
> +  data_[id] = insert(data_[id], key, &flag);
Не должно такого быть, так как id это число, взятое из combobox (которое называется maintreeId), а если если число есть в combobox, то такое дерево уже присутствует.

2023-03-30 10:58 UTC, rgolovachev commented on Core/model.h
> +  PNode<T> &operator[](int key) { return trees_[key]; }
Вообще я в своем коде предполагал, что когда зову operator[], то такой ключ уже существует. Заменил trees_[key] на trees_.at(key) теперь программа по идее должна упасть, если такого ключа нет.

2023-03-30 10:59 UTC, rgolovachev commented on Core/model.h
> +    return;
Да, просто в status bar'e (которое располагается внизу окна приложения) будет выведено сообщение об ошибке

2023-03-30 11:00 UTC, rgolovachev commented on Core/model.h
> +    data_[id] = new Node<T>{.par = nullptr,
Сделал так

2023-03-30 11:00 UTC, rgolovachev commented on Core/model.h
> +  std::string msg = "The left tree ID is " + std::to_string(id) +
Исправил это

2023-03-30 11:00 UTC, rgolovachev commented on Core/model.h
> +    port_out_->Set(std::make_pair(StrMsg[MsgCode::FOUND], data_.Get()));
Нет, задваивания не будет

2023-03-30 11:01 UTC, rgolovachev commented on Core/model.h
> +    set_color(v, v->par->par->left, v->left, v->right, v->par->right);
Исправил название на set_state

2023-03-30 11:02 UTC, rgolovachev commented on Core/vnode.h
> +constexpr const int kRadius = 6;
Засунул эти константы + методы Fill* в класс ReadyTree, который менеджит готовое для отрисовки дерево.

2023-03-30 11:03 UTC, rgolovachev commented on Core/controller.h
> +    port_in_.reset(new Observer{observable, lambda});
Исправил

2023-03-30 11:03 UTC, rgolovachev commented on Core/controller.h
> +      if (msg.type == QueryType::INSERT) {
Исправил

2023-03-30 11:04 UTC, rgolovachev commented on Core/controller.h
> +    auto lambda = [this](const std::any &msg_) {
Исправил

2023-03-30 11:07 UTC, rgolovachev commented on Core/view.h
> +
Спрятал StateToClr в класс Palette (плюс перетащил туда метод GetColor из View). Кроме того, спрятал StrMsg (которое раньше было в node.h) в класс Text и перетащил туда некоторые методы из View и сделал их статическими.

2023-03-30 11:07 UTC, rgolovachev commented on Core/view.h
> +// определить макрос Q_OBJECT
Теперь Model, View и Controller нешаблонные

2023-03-30 11:07 UTC, rgolovachev commented on Core/view.h
> +  if (std::is_same_v<T, int>) {
Убрал шаблонность ну и убрал метод ConvertString

2023-03-30 11:08 UTC, rgolovachev commented
Все готово, теперь можно проверять

2023-03-30 13:51 UTC, DimaTrushin requested changes
Из глобального:
1) Предлагаю перейти на std::map<int, Node<T>>, чтобы была value semantics и не придется самому возиться с памятью. Только надо следить за узлами.
2) Еще обнаружил несколько ненужных копирований деревьев.
3) Несколько багов в обзервере (не знаю, как у тебя не упал код).
4) Еще я мог сделать несколько замечаний по организации view, но думаю, что для текущего проекта такой имплементации будет достаточно.

В целом мне опять все нравится. Надо лишь поправить некоторые детали.

2023-03-30 13:51 UTC, DimaTrushin commented on DSViz.pro
> +# решил забить на исключения, qwt вроде не должна их бросать
Если хочешь выключить исключения, в qmake есть специальный флаг, который гарантирует для любой платформы их отключение. Надо написать.
CONFIG += exceptions_off

2023-03-30 13:51 UTC, DimaTrushin commented on DSViz.pro
> +win32-msvc*|win64-msvc* {
win64 нет такой платформы, если я правильно помню. Есть win32 и winrt. Потому можно написать
win*-msvc* {...}

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
> +  void Set(const T &msg) {
Добавь еще метод
```cpp
void Set(T&& msg) {
  msg_ = std::move(msg);
  Notify();
}
```

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
> +  void Unsubscribe(bool do_detach = true) {
Плохая идея делать такую функцию. Потому что с вызовом unsubscribe(false) у тебя объект остается в некорректном состоянии: он думает, что он не подсоединн к observable, а observable все еще хранит его в своем списке.
Я виже где тебе это надо, в деструкторе observable. Но ты вместо этого можешь просто вызывать unsubscribe в деструкторе observable, а тут всегда вызывать detach. Тогда у тебя все всегда будет работать.

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
> +      (*list_observer_.begin())->Unsubscribe(false);
Можно сделать просто 
```cpp
while(!list_observer_.empty())
  list_observer_->front().unsubscribe();
```
И все, и пусть observer сам зовет detach и сам отписывается.

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
> +    list_observer_.push_back(observer);
Плохая тема. Ты не сообщаешь observer-у, чтобы он у себя установил указатель на observable. Надо добавить что-то вроде
```cpp
observer->setObservable(this);
```
Иначе у тебя объекты в рассинхроне.

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
> +    if (observable_) {
Лучше создать метод isSubscribe() и тут его вызывать. Будет более понятно, что происходит.

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
> +    if (observable_) {
Глобально тут лучше вызывать метод unsubscribe и не думать. Пусть он внутри делает все проверки.

2023-03-30 13:51 UTC, DimaTrushin commented on Observer/observer.h
- Стало сильно лучше, но появились некоторые баги рассинхрона. Я про них написал.
- Кроме того, теперь у тебя в интерфейсах observer и observable есть безопасные и не безопасные методы. Надо сделать их друзьями друг друга и скрыть все небезопасные методы.
- В публичном интерфейсе observable должны остаться конструкторы, деструктор, subscribe и set. А еще надо удалить все копи и мув конструкторы и операторы (все четыре штуки). Чтобы случайно не переместить в памяти. Иначе у тебя накроются указатели.
- В публичном интерфейсе observer должны остаться конструкторы, деструктор, unsubscribe и все. Аналогично надо удалить копирование и перемещение. Чтобы можно было надежно пользоваться указателями.

2023-03-30 13:51 UTC, DimaTrushin commented on App/app.h
> +  // я верю что это влезет на стек
Да, в этом случае можно не париться.

2023-03-30 13:51 UTC, DimaTrushin commented on App/app.cpp
> +  model_.GetPortOut()->Subscribe(view_.GetPortIn());
Тут идейное замечание. Когда ты видишь код вида object1->object2->object3->function(), это значитя, что у тебя неверно настроен интерфейс object1. То есть либо ты должен был передать в функцию object1->object2 и из под нее вызвать функцию с аргументом object2->object3 и только в ней вызывать функцию последнего. То есть это нарушение уровня доступа и нарушение зоны ответственности. Ты должен всегда взаимодействовать напрямую с интерфейсом объекта, а не писать такие длинные цепочки.
Я бы тут вместо GetPortOut имплементировал функцию Subscribe. Дело в том, что тебе порт нужен только для подписания к нему. И более того, так ты можешь создать много разных портов и через SubscribeToSomething говорить явно на что ты подписываешься.

2023-03-30 13:51 UTC, DimaTrushin commented on App/mainwindow.cpp
У меня тоже LLVM сортировка инклудов. Если ты между ними поставишь пустую строку, то он их не перемешивает. То есть ты можешь так группировать сам блоки сортировки инклудов.

2023-03-30 13:51 UTC, DimaTrushin commented on App/mainwindow.cpp
> +MainWindow::~MainWindow() {}
Напиши = default;

2023-03-30 13:51 UTC, DimaTrushin commented on Common/node.h
>    INSERT_ERR,
Забыл такую штуку в прошлый раз сказать. Такой стиль обычно используется только для макросов (болшими буквами и через подчеркивание). Потому увидя в твоем коде такие имена люди скорее всего решат (да и я в том числе), что это макросы. Если ты используешь enum class, то у тебя ничего друг в друга не кастуется и имена не уплывают в глобальный namespace, потому тут можно использовать нормальные имена как для переменных. MsgCode::insert_error будет выглядеть куда лучше. Тут можно даже не сокращать.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.h
Я тут подумал, что погорячился и модель -- это единственное, что можно было оставить шаблонным. Но можно не мучиться уже. Извиняюсь =) Вот контроллер и вью точно должны быть не шаблонные.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.h
> +  ~Trees();
Вот тут очень тонкое место языка. Если ты определяешь деструктор, то у тебя определяется дефолтный конструктор и копирующий конструктор с копирующим присваиванием, но не объявляются мув конструктор с мув присваиванием. Лучше явно объявить дефолтный конструктор и удалить все копи и мув функции (все 4), потому что ты работаешь явно с указателями и у тебя все поедет, когда ты map скопируешь. Я так понимаю тебе move можно оставить.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.h
> +  void Destroy(int id);
Скрой этот метод, он деталь имплементации.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.h
> +  void Insert(std::pair<int, PNode<int>> tree);
Вот это выглядит как деталь имплементации. Ты точно хочешь вставлять данные именно так? Уж лучше вставлять как-то так
```cpp
void Insert(int id, {/*инициализация всех полей Node<int>*/})
```
Более того, тебе надо хранить std::unique_ptr<Node<int>>, а не голый указатель, тогда это будет value semantics и тебе не надо будет париться о выделении и удалении памяти вручную.

2023-03-30 13:51 UTC, DimaTrushin commented on Common/node.h
>  template <typename T> using BareTrees = std::map<int, PNode<T>>;
- Плохо, что ты так разнес все эти дефайны по разным файлам. Лучше все эти вещи внутри дерева сформулировать. Иначе их приходится искать. Это плохо. Я предпочитаю делать так. Каждый класс в самом начале в приватной зоне делает все using-ги для своей работы. Тогда эта информация локализована. Ты ее можешь подтягивать из других классов, но тогда не придется так бегать по определениям.
- Кроме того, лучше иметь std::map<int, Node<T>>; Тогда тебе не надо будет париться о памяти, только о корректности указателей. Дело в том, что std::map гарантирует, что указатели на его элементы не меняются в течение жизни. Я где-то про unique_ptr написал, но даже его не надо.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.h
> +class Model {
Очень хорошо, что отделил лес от модели, содержащей лес. Это правильная идея.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.h
> +  BareTrees<int> Get();
Это видимо надо для отрисовки?

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.cpp
> +size_t Trees::Size() { return trees_.size(); }
Этот метод должен быть константный.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.cpp
> +BareTrees<int> Trees::Get() { return trees_; }
Ты копию возвращаешь? Не константную ссылку?

2023-03-30 13:51 UTC, DimaTrushin commented on Core/model.cpp
> +void Trees::destroy(PNode<int> root) {
лучше переменную назвать node, ибо ты не только root можешь удалять. Иначе тебе нужна проверка на корень, а не на nullptr.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.h
> +  // constexpr сделать не выйдет, у std::map нет constexpr конструктора
Да, это печаль. Обычно в этом месте начинаются std::array и грязные касты enum-ов. Думаю, что так можно оставить.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.h
> +  static QString GetText(QComboBox *ptr);
Вот эта и следующие функции выглядят странно. То есть у тебя класс Text как бы намекает, что он работает с текстом и почему он при этом знает что-то про какие-то Qt-овские объекты. Это странно. Пока не видел имплементацию.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.h
> +  auto GetCallback();
А это так работает. Мне казалось, функции возвращяющие auto надо inline определять на месте. Могу ошибаться.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.h
> +  std::unique_ptr<MainWindow> MW_;
Мне надо будет подумать над тем, что ты сюда поместил MainWindow. Я думаю, что это реально правильная идея и у меня в моем приложении может быть сделано хуже.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.h
> +class View : public QObject {
В целом сделано хорошо. Но для больших проектов, надо будет делить view на более мелкие компоненты. Точнее это у тебя MainWindow на самом деле и внутри него можно выделять другие объекты, чтобы сгруппировать их функционал и не делать монстр-классы. Тут в этом нет необходимости.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +  return QColorConstants::Gray;
Можно еще ввести статическую константу DefaultColor. Но тут уже можно не париться.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +void Text::InsertItem(QComboBox *ptr, int num) {
Это не ответственность класса Text. Добавлять в себя визуальные элементы должна сама view. А у объекта Text view должна запрашивать описания.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +// высунул вперед, т.к. компилятор должен смочь вывести тип в auto
То есть это все таки работает =) Надо будет поиграться и еще раз глянуть cppreference.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +      panner_{std::make_unique<CustomPanner>(MW_->ui->qwt_plot->canvas())},
Сделай у MainWindow метод возвращающий qwt_plot, который тебе надо и тут сократится количество стрелочек.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +  port_out_.Set(UserQuery{QueryType::DO_NOTHING, {0, 0}});
Я могу потом рассказать, как я такие костыли обхожу.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +    merge_executing_ = true;
Это флаг гашения сигнала от модели?

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +void View::OnButtonClick() {
А ты тут все кнопки в одной функции обрабатываешь? Просто если ты определяешь явно сендера, то не проще было бы каждую кнопку связать со своим слотом?

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +  trees_ = trees;
Ты тут опять все дерево копируешь?

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +QwtSymbol *View::GetSymbol(PVNode vnode) {
А эта хрень точно должна создаваться в куче?

2023-03-30 13:51 UTC, DimaTrushin commented on Core/view.cpp
> +  timer_.start(sWait * 1000);
sWait * kSecondsPerMinute

2023-03-30 13:51 UTC, DimaTrushin commented on Core/controller.h
> +  void Insert(const ArgsType &args);
По-хорошему у контроллера нет публичных методов кроме конструктора и порта. Вся логика зашита внутрь и выполняется только по оповещению порта. Так что можно все методы закрыть (и нужно). Эти методы не должны использоваться напрямую. Только из порта.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/controller.cpp
> +// если что, компилятор требует от меня определить GetCallback заранее т.к. тип
Тогда его можно определеить первым в приватной зоне в начале класса.

2023-03-30 13:51 UTC, DimaTrushin commented on Core/controller.h
Контроллер мне очень понравился. Только надо закрыть почти все его методы кроме конструктора и порта.

2023-04-10 14:19 UTC, rgolovachev commented on DSViz.pro
> +# решил забить на исключения, qwt вроде не должна их бросать
Исправил

2023-04-10 14:19 UTC, rgolovachev commented on DSViz.pro
> +win32-msvc*|win64-msvc* {
Исправил

2023-04-10 14:20 UTC, rgolovachev commented on Observer/observer.h
> +  void Set(const T &msg) {
Добавил

2023-04-10 14:21 UTC, rgolovachev commented on Observer/observer.h
> +  void Unsubscribe(bool do_detach = true) {
убрал do_detach

2023-04-10 14:23 UTC, rgolovachev commented on Observer/observer.h
> +      (*list_observer_.begin())->Unsubscribe(false);
Из-за того, что я забывал прокинуть в observer указатель на observable этот цикл улетал в бесконечность. Добавил setObservable и теперь всё работает.

2023-04-10 14:23 UTC, rgolovachev commented on Observer/observer.h
> +    list_observer_.push_back(observer);
добавил

2023-04-10 14:23 UTC, rgolovachev commented on Observer/observer.h
> +    if (observable_) {
создал isSubscribe

2023-04-10 14:24 UTC, rgolovachev commented on Observer/observer.h
> +    if (observable_) {
исправил

2023-04-10 14:26 UTC, rgolovachev commented on App/app.cpp
> +  model_.GetPortOut()->Subscribe(view_.GetPortIn());
Создал SubscribeToView в Model и SubscribeToController в View.

2023-04-10 14:26 UTC, rgolovachev commented on App/mainwindow.cpp
> +MainWindow::~MainWindow() {}
написал

2023-04-10 14:26 UTC, rgolovachev commented on Common/node.h
>    INSERT_ERR,
перевел все енумы в lowercase

2023-04-10 14:27 UTC, rgolovachev commented on Core/model.h
> +  ~Trees();
вырезал эти 4 функции

2023-04-10 14:28 UTC, rgolovachev commented on Core/model.h
> +  void Destroy(int id);
Вместо Destroy и Erase создал один публичный метод DeleteTree (публичный он, потому что вызывается в Model::DeleteTree)

2023-04-10 14:32 UTC, rgolovachev commented on Core/model.h
> +  void Insert(std::pair<int, PNode<int>> tree);
Поправил интерфейс Insert. Я не хочу делать дерево на std::unique_ptr это, во-первых, медленней будет работать и, во-вторых, мне придется весь код модели перелопачивать))

2023-04-10 14:36 UTC, rgolovachev commented on Common/node.h
>  template <typename T> using BareTrees = std::map<int, PNode<T>>;
Ладно, перетащил эти юзинги в классы.
Не понял второе замечание, ты получается предлагаешь сделать дерево не на указателях или как?

2023-04-10 14:36 UTC, rgolovachev commented on Core/model.h
> +  BareTrees<int> Get();
Да

2023-04-10 14:36 UTC, rgolovachev commented on Core/model.cpp
> +size_t Trees::Size() { return trees_.size(); }
Исправил

2023-04-10 14:37 UTC, rgolovachev commented on Core/model.cpp
> +BareTrees<int> Trees::Get() { return trees_; }
Теперь константную ссылку)

2023-04-10 14:37 UTC, rgolovachev commented on Core/model.cpp
> +void Trees::destroy(PNode<int> root) {
Переименовал

2023-04-10 14:37 UTC, rgolovachev commented on Core/view.cpp
> +  return QColorConstants::Gray;
Ввел

2023-04-10 14:38 UTC, rgolovachev commented on Core/view.cpp
> +void Text::InsertItem(QComboBox *ptr, int num) {
Перетащил статические методы, которые работают с qt объектами в класс View.

2023-04-10 14:39 UTC, rgolovachev commented on Core/view.cpp
> +      panner_{std::make_unique<CustomPanner>(MW_->ui->qwt_plot->canvas())},
Сделал

2023-04-10 14:51 UTC, rgolovachev commented on Core/view.cpp
> +    merge_executing_ = true;
Этот флаг нужен только в View::Prepare для того чтобы понять, какое дерево визуализировать. Если merge_executing_ == false, то я закидываю в метод Fill дерево с номером, которое указано в одном combobox (MW_->ui->maintreeId), а если true, то беру номер из другого combobox (MW_->ui->lefttreeId). Если посмотреть, как выглядит GUI в ридми, то наверное станет ясным, из каких combobox я беру эти значения. Fill считает, какие координаты должны быть у вершин дерева на полотне.

2023-04-10 14:52 UTC, rgolovachev commented on Core/view.cpp
> +void View::OnButtonClick() {
Ну я так подумал, что в итоге получится меньше кода, если все сигналы от кнопок будет обрабатывать один метод, который в зависимости от значения sender() выбирает что делать с сигналом.

2023-04-10 14:58 UTC, rgolovachev commented on Core/view.cpp
> +  trees_ = trees;
Да, но я думаю это не страшно

2023-04-10 15:02 UTC, rgolovachev commented on Core/view.cpp
> +QwtSymbol *View::GetSymbol(PVNode vnode) {
Да, иначе программа упадет в строчке 306 (plot->detachItems()). Эта функция (если я ничего не путаю) вызывает delete от указателей на объекты, которые прикреплены к plot (в том числе она вызовет delete на QwtSymbol*).

2023-04-10 15:02 UTC, rgolovachev commented on Core/view.cpp
> +  timer_.start(sWait * 1000);
Исправил

2023-04-10 15:02 UTC, rgolovachev commented on Core/controller.h
> +  void Insert(const ArgsType &args);
Спрятал лишние методы

2023-04-10 15:03 UTC, rgolovachev commented on Core/controller.cpp
> +// если что, компилятор требует от меня определить GetCallback заранее т.к. тип
Сделал так

2023-04-11 14:00 UTC, DimaTrushin requested changes
Остались совсем небольшие замечания.
1) Написал про косяк с observable subscribe, про который я зыбал в прошлый раз написать.
2) Есть небольшая деталь с хранением данных во view.
3) Все остальное небольшие мелочи.
Плюс добавил всякие рассуждения местами.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/model.h
> +  void SubscribeToView(Observer<Model::MsgType> *view_observer);
Тут можно вместо Model::MsgType написать MsgType для краткости. Ты же внутри модели, тебе не надо к имени по квалификатору обращаться.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.cpp
> +    merge_executing_ = true;
Ок, понял, как это работает. Тут вот что скажу, это плохая тема брать данные из combobox. По-хорошему эти состояния должны храниться не в графическом интерфейсе, а хотя бы здесь внутри View как данные. А в графическом интерфейсе ты лишь отображаешь их. В идеальном мире View вообще stateless и ничего не хранит. В этом случае должна быть ViewModel, которая получает данные из модели и по ней достраивает модель которую уже можно отрисовать и только потом оповещает View. В этом смысле текущий дизайн -- это слияние внутри View классического stateless View и ViewModel. Не надо сейчас эту логику менять. Для текущего проекта такой подход работает достаточно хорошо. Но при этом если ты во View хочешь хранить данные, не храни их в графическом интерфейсе, а храни в полях View, а в графическом интерфейсе лишь отрисовывай их.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.cpp
> +  MW_->GetPlot()->setAxisScale(QwtPlot::xBottom, -kBound / scale_,
Тут сейчас будет рассуждение в слух. Я не ожидаю в связи с ним каких-то правок, но считаю, что озвучить надо. Я продвигаю подход, что все функции должны содержать один глагол. Это в целом хорошая идея, но она плохо работает в случае, когда функция дает доступ к данным класса (типо property). И вот в этом случае люди предпочитают не использовать глаголы, потому что Plot() и Plot_ по сути дают доступ к объекту и тут глагол не нужен. Это информация тебе на помедетировать, где что лучше использовать. И в будущем понять, как тебе больше кажется правильным.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.cpp
> +  trees_ = trees;
А почему нельзя просто к нему по константной ссылке обращаться? Зачем тебе еще одна копия оригинального дерева? Просто если ты не хочешь дерево передавать явно через аргументы функции, можешь использовать указатель на константное дерево.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.cpp
> +QwtSymbol *View::GetSymbol(PVNode vnode) {
Ага, понял. То есть где-то происходит передача ownership объекту plot. Я просто все с exception safe мышлением рассуждаю. И когда где-то выделили память, пока объект не имеет owner-а, я все стараюсь хранить в std::unique_ptr, а как только выставляю owner-а, то тут же его освобождаю из unique_ptr через release.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.h
> +  void SubscribeToController(Observer<UserQuery> *controller_observer);
SubscribeToUserInput
Ты все таки подписываешься не к контроллеру, а контоллер подписсываешь. А название надо выбирать вот из каких соображений. Представь у тебя есть несколько observable тут в этом объекте, и ты хочешь их отличать. Как ты их отличаешь? По тому, откуда данные. В данном случае это данные от пользовательского ввода.

2023-04-11 14:00 UTC, DimaTrushin commented on DSViz.pro
> +win*-msvc* {
Я бы добавил такую строчку
```cpp
CONFIG(debug, debug|release) {
  ## код для дебага
} else {
  ## код для релиза
}
```

2023-04-11 14:00 UTC, DimaTrushin commented on Observer/observer.h
>    void Subscribe(Observer<T> *observer) {
Я тут в прошлый раз хотел написать совсем про другой косяк, но потом обнаружил рассинхрон и забыл. Дело в том, что тебе еще надо проверить подписан ли обзервер на кого-то. Вдруг ты его переподписываешь? Тогда будет что-то вроде
```cpp
if (observer->isSubscribed())
  observer->Unsubscribe();
```
При этом подписан или нет можно определять ялвяется ли указатель на observable nullptr или нет.

2023-04-11 14:00 UTC, DimaTrushin commented on Observer/observer.h
> +  Observer(LambdaType lmbd) : observable_{}, lmbd_{lmbd} {}
lmbd_{std::move(lmbd)}
Если уж принимаешь в конструктор данные by value, то их надо move-ать внутрь объекта.

2023-04-11 14:00 UTC, DimaTrushin commented on Observer/observer.h
> +  bool IsSubscribed() const { return observable_; }
этот метод лучше сделать публичным. Все таки пользователь класса должен уметь проверить, соединен ли их порт.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/model.h
> +  void SubscribeToView(Observer<Model::MsgType> *view_observer);
Название, лучше написать SubscribeToBareTree или что-то в этом духе.

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.cpp
> +  QObject::disconnect(maintreeId, SIGNAL(currentTextChanged(QString)), this,
Я правильно понимаю, что дисконектить приходится потому что когда ты программно выставляешь, все равно обратка приходит? То есть Qt не отличает программных сигналов и сигналов пользователя?

2023-04-11 14:00 UTC, DimaTrushin commented on Core/view.cpp
> +    cur_tree_.Fill(trees_[MW_->ui->maintreeId->currentText().toInt()]);
Да, вот это место, не очень хорошо, читать данные из интерфейса. Текущее дерево, или что там хранится, должно явно храниться у тебя в теле View.

2023-04-11 14:00 UTC, DimaTrushin commented on DSViz.pro
> +### comment this when push
Я обычно делаю один макрос и им контролирую такие вещи. Например
```cpp
DEFINE += MYDEBUG

contains(DEFINES, MYDEBUG) {
  SOURCES += Debug/debug.cpp
  HEADERS += Debug/debug.h
}
```
Тогда комментированием одной строки отключается все.

2023-04-12 20:27 UTC, rgolovachev commented on Core/model.h
> +  void SubscribeToView(Observer<Model::MsgType> *view_observer);
Да, видимо по невнимательности запихнул Model::, убрал

2023-04-12 20:32 UTC, rgolovachev commented on Core/view.cpp
> +    merge_executing_ = true;
Да, согласен, тема так себе. В общем завел еще три поля в классе View: `main_tree_id_`, `left_tree_id_` и `right_tree_id_` в которых храню информацию о выбранных деревьях. Еще теперь у меня слоты принимают сигналы от combobox (в случае выбора юзером другого дерева) ну и меняют соответствующим образом эти три переменные.

2023-04-12 20:33 UTC, rgolovachev commented on Core/view.cpp
> +  MW_->GetPlot()->setAxisScale(QwtPlot::xBottom, -kBound / scale_,
Я думаю действительно лучше Plot назвать эту функцию, так что я переименовал

2023-04-12 20:34 UTC, rgolovachev commented on Core/view.cpp
> +  trees_ = trees;
Теперь во View храню не `BareTrees` а `const BareTrees *`

2023-04-12 20:35 UTC, rgolovachev commented on Core/view.h
> +  void SubscribeToController(Observer<UserQuery> *controller_observer);
Логично, переименовал

2023-04-12 20:39 UTC, rgolovachev commented on DSViz.pro
> +win*-msvc* {
Ок, давай так. В дебажную версию я еще добавил debug.cpp и debug.h (вообще я их уже не юзаю, но пусть будут, там просто функция, которая выводит сообщения в файл). В релизе я включаю на полную оптимизации (O3 если g++ или clang и /O2 если msvc)

2023-04-12 20:42 UTC, rgolovachev commented on Observer/observer.h
>    void Subscribe(Observer<T> *observer) {
Ок, исправил

2023-04-12 20:43 UTC, rgolovachev commented on Observer/observer.h
> +  Observer(LambdaType lmbd) : observable_{}, lmbd_{lmbd} {}
Исправил

2023-04-12 20:43 UTC, rgolovachev commented on Observer/observer.h
> +  bool IsSubscribed() const { return observable_; }
Сделал публичным

2023-04-12 20:43 UTC, rgolovachev commented on Core/model.h
> +  void SubscribeToView(Observer<Model::MsgType> *view_observer);
Ок, давай так

2023-04-12 20:44 UTC, rgolovachev commented on Core/view.cpp
> +  QObject::disconnect(maintreeId, SIGNAL(currentTextChanged(QString)), this,
Да, все так. Там я создал отдельные функции`DisconnectComboBoxes` и `ConnectComboBoxes`, а то там уже disconnect и connect нужно писать теперь для всех трех комбобоксов.

2023-04-12 20:45 UTC, rgolovachev commented on Core/view.cpp
> +    cur_tree_.Fill(trees_[MW_->ui->maintreeId->currentText().toInt()]);
Теперь хранится

2023-04-12 20:45 UTC, rgolovachev commented on DSViz.pro
> +### comment this when push
запихнул debug.cpp и debug.h в дебажную сборку проекта, не знаю насколько это хорошая идея

2023-04-15 14:21 UTC, DimaTrushin approved these changes
Написал пару мелочей в качестве замечаний. Из самого важно -- там в одном месте ты все еще хранишь информацию в интерфейсе. Но в целом я решил одобрить пуллреквест.

2023-04-15 14:21 UTC, DimaTrushin commented on Core/view.cpp
> +void View::UpdateTreeId(int &tree_id) {
Мне обычно не нравится, когда изменяемые данные передаются по ссылке, а не по указателю. Тогда пользователь функции просто не видит, что данные меняются.

2023-04-15 14:21 UTC, DimaTrushin commented on Core/view.cpp
> +  // если дерева с номером tree_id уже не существует, то отрисовываю первое
По-хорошему, данные для отрисовки должны строиться корректно перед подачей на вход для View. И она должна просто по ним отрисовать. Странно, что тут такая логика понадобилась. Это когда-то случается?

2023-04-15 14:21 UTC, DimaTrushin commented on Core/model.cpp
> +// здесь хренотень какая-то происходит, из-за чего падает merge
Этот комментарий теперь можно убрать? DiscardTree решило проблему?

2023-04-15 14:21 UTC, DimaTrushin commented on Debug/debug.h
> +static void WriteLog(const std::string &str);
Нет смысла в header-е делать статические функции. Они и так будут глобальными.

2023-04-15 14:21 UTC, DimaTrushin commented on Core/view.cpp
> +bool View::DoDelay(MsgCode code) {
Лучше NeedDelay так название лучше отражает, что происходит.

2023-04-15 14:21 UTC, DimaTrushin commented on Core/view.cpp
> +    Delay(MW_->ui->delayTime->value());
Тут опять хранишь значение в интерфейсе. Но тут надо сказать, что Qt-овские приминивы не stateless, так что они хранят значения. Другой вопрос, а там значение всегда корректное?

2023-04-15 14:21 UTC, DimaTrushin commented on Core/model.cpp
> +void Model::SubscribeToBareTree(Observer<Model::MsgType> *view_observer) {
MsgType у тебя должен быть виден внутри модели, можено без Model::

2023-04-30 21:01 UTC, merged